config {
    type: "incremental",
    schema: data.silver_schema,
    name: data.tab_ft_ga4,
    assertions: {
        nonNull: ["event_date", "event_name", "user_pseudo_id", "ga_session_id"],
        rowConditions: [
            "event_timestamp > 0"
        ]
    },
    description: "Trusted Layer: Eventos GA4 consolidados (Daily + Intraday) com priorizacao e idempotencia.",
    tags: ["silver", "ga4", "trusted", "full", "marketing", "retail"],
    bigquery: {
        partitionBy: "event_date",
        labels: {
            "layer": "silver"
        },
        clusterBy: ["event_name", "ga_session_id"],
        updatePartitionFilter: `event_date >= date_sub(current_date(), interval ${data.lookback_days} day)`
    }
}

WITH all_sources AS (
    SELECT
        parse_date('%Y%m%d', event_date) AS event_date,
        event_timestamp,
        event_name,
        user_pseudo_id,
        (SELECT value.int_value FROM UNNEST(event_params) WHERE key = 'ga_session_id') AS ga_session_id,
        IF(regexp_contains(_TABLE_SUFFIX, 'intraday'), 2, 1) AS source_priority,
        CURRENT_TIMESTAMP() AS atualization_date
    FROM
        `${data.raw_ga4_project}.${data.raw_ga4_dataset}.events_*`
)

SELECT
    to_hex(sha256(concat(
        cast(event_timestamp as string), 
        event_name, 
        user_pseudo_id, 
        cast(ga_session_id as string)
    ))) AS surrogate_key,
    * EXCEPT(source_priority, atualization_date, rn),
    atualization_date
FROM (
    SELECT 
        *,
        ROW_NUMBER() OVER(
            PARTITION BY event_timestamp, event_name, user_pseudo_id, ga_session_id
            ORDER BY source_priority ASC, atualization_date DESC
        ) as rn
    FROM all_sources
)
WHERE rn = 1